FROM python:3.14.3-alpine

RUN apk add --no-cache curl
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv
COPY pyproject.toml uv.lock ./

RUN uv sync --link-mode=copy

COPY . .

CMD ["uv", "run", "./video_platform/manage.py", "runserver", "0.0.0.0:8000"]